<a href="https://colab.research.google.com/github/jarodchristiansen/PythonProjects/blob/master/3rd_Sklearn_(First_Multi_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade -q gspread
!pip install gspread-dataframe

These requirements should normally be satisfied, they are dependencies for gspread to pull the dataframe

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn
seaborn.set()
import gspread
from gspread_dataframe import get_as_dataframe, set_with_dataframe

from sklearn.linear_model import LinearRegression

Import necessary libraries to create dataframe, regression, and formatting of regression (plotting) Gspread creates dataframe from sheets file

In [ ]:
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())

This will create authorization through google sheets (follow link that appears and copy authorization code)

In [ ]:
sheet1 = gc.open_by_url('https://docs.google.com/spreadsheets/d/1Kljn-lQAhMrjyuf_3JEPQ-lU6Am9dWZSdJDEVOV8UwM/edit#gid=0')

sheet1 is entire csv file URL is sheets file URL

In [ ]:
ws = sheet1.worksheet('Data')

This is the tab in csv file

In [ ]:
data = get_as_dataframe(ws)

titles the dataframe extracted from sheets file

In [ ]:
data

SAT  Rand 1,2,3   GPA  ...  Unnamed: 23  Unnamed: 24  Unnamed: 25
0    1634.0         2.0  3.42  ...          NaN          NaN          NaN
1    1663.0         3.0  3.20  ...          NaN          NaN          NaN
2    1664.0         3.0  2.52  ...          NaN          NaN          NaN
3    1670.0         1.0  2.91  ...          NaN          NaN          NaN
4    1674.0         2.0  3.17  ...          NaN          NaN          NaN
..      ...         ...   ...  ...          ...          ...          ...
994     NaN         NaN   NaN  ...          NaN          NaN          NaN
995     NaN         NaN   NaN  ...          NaN          NaN          NaN
996     NaN         NaN   NaN  ...          NaN          NaN          NaN
997     NaN         NaN   NaN  ...          NaN          NaN          NaN
998     NaN         NaN   NaN  ...          NaN          NaN          NaN

[999 rows x 26 columns]

This is calling the dataframe and representing from Pandas. NaN cells are empty values

In [ ]:
data.dropna(axis=0, how='all', inplace=True)

dropna() is a methodfrom Pandas to remove NaN cells, axis=0 is rows how is any or all, inplace True removes from the dataframe

In [ ]:
data.dropna(axis=1, how='all', inplace=True)

dropna() is a methodfrom Pandas to remove NaN cells, axis=1 is columns how is any or all, inplace True removes from the dataframe

In [ ]:
data

SAT  Rand 1,2,3   GPA
0   1634.0         2.0  3.42
1   1663.0         3.0  3.20
2   1664.0         3.0  2.52
3   1670.0         1.0  2.91
4   1674.0         2.0  3.17
..     ...         ...   ...
79  2020.0         1.0  3.28
80  2020.0         2.0  3.65
81  2021.0         3.0  3.61
82  2041.0         3.0  3.51
83  2050.0         2.0  3.81

[84 rows x 3 columns]

calls the corrected dataframe

In [ ]:
x = data[['SAT', 'Rand 1,2,3']]
y = data ['GPA']

sets the target (y) and feature (x)

formats the 1 dimensional array of x to a matrix

In [ ]:
reg = LinearRegression()

reg becomes a variable corresponding to the linearRegression function so it can be called as such

In [ ]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

copy_X indicates that it is a copy of x_matrix. Intercept (constant) is automatically calculated and can be analyzed.

In [ ]:
reg.score(x,y)

0.4066811952814285

R Squared (effectiveness of the prediction. 1 is max = 100%. Adjusted R squared is more indicative. Adding more, relevant variables will improve this.

In [ ]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]


adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)

n = the number of observations 
p = the number of predictors

In [ ]:
adjusted_r2

0.39203134825134023

In [ ]:
from sklearn.feature_selection import f_regression
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

first array if f-statistics
second array is pvalues

In [ ]:
p_values = f_regression(x,y)[1]
p_values 
p_values.round(3)

array([0.   , 0.676])

In [ ]:
reg.coef_

array([ 0.00165354, -0.00826982])

yhat = coef*x+intercept

In [ ]:
reg.intercept_

0.2960326126490944

provides the constant of the regression

In [ ]:
reg.predict([])

runs the prediction for the variable of 750 sq. ft provided. can also be added via Dataframe that is custom created. 

In [ ]:
plt.scatter(x, y)
yhat = reg.coef_*x_matrix +reg.intercept_
fig = plt.plot(x,yhat, lw=4, c='orange', label ='regression line')
plt.xlabel('SAT', fontsize = 20)
plt.ylabel('GPA', fontsize = 20)
plt.show()