<a href="https://colab.research.google.com/github/jarodchristiansen/PythonProjects/blob/master/ChatbotV_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pickle
import numpy as np
import pandas as pd
import requests

In [ ]:
train_data = requests.get('http://convai.io/data/data_tolokers.json').json()

In [ ]:
data = pd.DataFrame()

In [ ]:
train_data

[{'bot_profile': ['i have amazing children and grandchildren.',
   'i can sew my own clothes.',
   'i had cancer but its gone now.',
   'i am retired and living the great life.',
   'i do not have a smartphone.'],
  'dialog': [{'evaluation_score': None,
    'id': 0,
    'sender': 'participant2',
    'sender_class': 'Bot',
    'text': 'I love iphone! i just bought new iphone!'},
   {'evaluation_score': None,
    'id': 1,
    'sender': 'participant1',
    'sender_class': 'Human',
    'text': "Thats good for you, i'm not very into new tech"},
   {'evaluation_score': None,
    'id': 2,
    'sender': 'participant2',
    'sender_class': 'Bot',
    'text': 'I am a college student and i am a college student'},
   {'evaluation_score': None,
    'id': 3,
    'sender': 'participant1',
    'sender_class': 'Human',
    'text': 'I am go to gym and live on donations'},
   {'evaluation_score': None,
    'id': 4,
    'sender': 'participant2',
    'sender_class': 'Bot',
    'text': 'I am a vegan and i a

In [ ]:
train_data[3126]

{'bot_profile': ['i work for our local supermarket.',
  'my favorite band is the who.',
  'i have never been out of ohio.',
  'my favorite food is pizza with black olives.'],
 'dialog': [{'evaluation_score': None,
   'id': 0,
   'sender': 'participant2',
   'sender_class': 'Bot',
   'text': 'Yo, how is your life?'},
  {'evaluation_score': None,
   'id': 1,
   'sender': 'participant2',
   'sender_class': 'Bot',
   'text': 'Time to give me 5 stars :)'},
  {'evaluation_score': None,
   'id': 2,
   'sender': 'participant1',
   'sender_class': 'Human',
   'text': 'Not so good'},
  {'evaluation_score': None,
   'id': 3,
   'sender': 'participant2',
   'sender_class': 'Bot',
   'text': 'so you do not want anyone taking interest in you  '},
  {'evaluation_score': None,
   'id': 4,
   'sender': 'participant1',
   'sender_class': 'Human',
   'text': 'I want'},
  {'evaluation_score': None,
   'id': 5,
   'sender': 'participant2',
   'sender_class': 'Bot',
   'text': 'same'},
  {'evaluation_score'

In [ ]:
with open('train_qa.txt', 'rb') as f:
    train_data = pickle.load(f)

In [ ]:
with open('test_qa.txt', 'rb') as f:
    test_data = pickle.load(f)

In [ ]:
len(train_data)

10000

In [ ]:
len(test_data)

1000

In [ ]:
train_data[0]

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

this is the loaded data from the split txt files of test and training data it is split into stories, questions, and answers in the form of a list featuring tuples

In [ ]:
' '.join(train_data[0][0])

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

this is indicating the first item in the list and the first component of that tuple or the first story

In [ ]:
' '.join(train_data[0][1])

'Is Sandra in the hallway ?'

In [ ]:
train_data[0][2]

'no'

In [ ]:
all_data = test_data + train_data

In [ ]:
len(all_data)

11000

In [ ]:
vocab = set()

for story,question,answer in all_data:
   vocab = vocab.union(set(story))
   vocab = vocab.union(set(question))

In [ ]:
vocab.add('no')

vocab.add('yes')

vocab_len = len(vocab) + 1

vocab_len

38

this is setting adding the answers to the vocab, note we add 1 to the lenght of the vocab_len to account for keras padding that will be handled later

In [ ]:
#longest story
all_story_lens = [len(data[0]) for data in all_data]

this is a list comprehension to find the len of each story in the entire dataset

In [ ]:
max_story_len = max(all_story_lens)

this is the longest story in the dataset

In [ ]:
max_question_len = max([len(data[1]) for data in all_data])

max_question_len

6

this is getting the longest question as well

In [ ]:
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [ ]:
tokenizer = Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)

this is using the keras tokenizer and using a fit on the vocab data to enable futher functionality that a tokenizer generally provides like index and frequency

In [ ]:
tokenizer.word_index

{'.': 17,
 '?': 37,
 'apple': 25,
 'back': 12,
 'bathroom': 9,
 'bedroom': 11,
 'daniel': 14,
 'discarded': 36,
 'down': 19,
 'dropped': 2,
 'football': 1,
 'garden': 6,
 'got': 30,
 'grabbed': 22,
 'hallway': 3,
 'in': 13,
 'is': 35,
 'john': 34,
 'journeyed': 18,
 'kitchen': 10,
 'left': 4,
 'mary': 33,
 'milk': 28,
 'moved': 21,
 'no': 26,
 'office': 15,
 'picked': 32,
 'put': 5,
 'sandra': 29,
 'the': 27,
 'there': 20,
 'to': 16,
 'took': 31,
 'travelled': 24,
 'up': 8,
 'went': 23,
 'yes': 7}

In [ ]:
train_story_text = []
train_question_text = []
train_answers = []

In [ ]:
for story, question, answer in train_data:
      train_story_text.append(story)
      train_question_text.append(question)
      train_answers.append(answer)

In [ ]:
train_story_seq = tokenizer.texts_to_sequences(train_story_text)

len(train_story_seq)


len(story)

62

The above 3 cells are one methodology to seperate the data acording to story, question, and answer as well as tokenize it into text and sequences, another approach will be used instead though with a customized funciton

In [ ]:
#train_story_seq

In [ ]:
#train_story_text

In [ ]:

def vectorize_stories(data,word_index=tokenizer.word_index,max_story_len=max_story_len,max_question_len=max_question_len):
     
    #stories = X
    X = []
    #questions = Xq
    Xq = []
    #Y correct answer (yes,no)
    Y = []
    for story,query,answer in data:
     	      
     x = [word_index[word.lower()] for word in story]
     xq = [word_index[word.lower()] for word in query]
    
     y = np.zeros(len(word_index)+1)
    
     y[word_index[answer]] = 1

     X.append(x)
     Xq.append(xq) 
     Y.append(y)

    return (pad_sequences(X,maxlen=max_story_len),pad_sequences(Xq,maxlen=max_question_len),np.array(Y))  

this function takes in the data, the index of a word, the length of the story and the length of the question. 

This will then create a tokenized index for each word that is then added to a corresponding list for story, question, and y= an array of generated 0's with 1 answered in. The returning pad sequences relays the arrays for each piece of data input

In [ ]:
inputs_train, queries_train, answers_train = vectorize_stories(train_data)

inputs_test, queries_test, answers_test = vectorize_stories(test_data) 

inputs_test

array([[ 0,  0,  0, ..., 27, 11, 17],
       [ 0,  0,  0, ..., 27,  6, 17],
       [ 0,  0,  0, ..., 27,  6, 17],
       ...,
       [ 0,  0,  0, ..., 27, 25, 17],
       [ 0,  0,  0, ..., 27,  6, 17],
       [ 0,  0,  0, ..., 25, 20, 17]], dtype=int32)

this is the np array for the inputs corresponding to the test data

In [ ]:
answers_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

this is the np array for the answers corresponding to the test data

In [ ]:
tokenizer.word_index['yes']

7

In [ ]:
tokenizer.word_index['no']

26

In [ ]:
sum(answers_test)

array([  0.,   0.,   0.,   0.,   0.,   0.,   0., 497.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0., 503.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [ ]:
from keras.models import Sequential,Model


from keras.layers.embeddings import Embedding


from keras.layers import Input, Activation, Dense, Permute, Dropout,add,dot,concatenate, LSTM


#placeholder shape = (max_story_len,batch_size)
input_sequence = Input((max_story_len,))
question = Input((max_question_len,))


vocab_size = len(vocab) + 1

In [ ]:

#input encoder m
input_encoder_m = Sequential()
input_encoder_m.add(Embedding(input_dim=vocab_size,output_dim=64))
input_encoder_m.add(Dropout(0.3))

# (samples,story_maxlen,embedding_dim)


#input encoder c
input_encoder_c = Sequential()
input_encoder_c.add(Embedding(input_dim=vocab_size,output_dim=max_question_len))
input_encoder_c.add(Dropout(0.3))

# (samples,story_maxlen,max_question_len)


#question encoder 
question_encoder = Sequential()
question_encoder.add(Embedding(input_dim=vocab_size,output_dim=64))
question_encoder.add(Dropout(0.3))

In [ ]:
# (samples,query_maxlen,embedding_dim)

input_encoded_m = input_encoder_m(input_sequence)
input_encoded_c = input_encoder_c(input_sequence)
question_encoded = question_encoder(question)

In [ ]:
match = dot([input_encoded_m, question_encoded], axes=(2,2))
match = Activation('softmax')(match)

In [ ]:
response = add([match,input_encoded_c])
response = Permute((2,1))(response)

In [ ]:
answer = concatenate([response,question_encoded])

In [ ]:
answer

<tf.Tensor 'concatenate_1/concat:0' shape=(None, 6, 220) dtype=float32>

In [ ]:
answer = LSTM(32)(answer)


answer = Dropout(0.5)(answer)
answer = Dense(vocab_size)(answer) #(samples, vocab_size) # Yes/no 000


answer = Activation('softmax')(answer)


model = Model([input_sequence,question],answer)


model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])


model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 156)          0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 6)            0                                            
__________________________________________________________________________________________________
sequential_1 (Sequential)       multiple             2432        input_1[0][0]                    
__________________________________________________________________________________________________
sequential_3 (Sequential)       multiple             2432        input_2[0][0]                    
____________________________________________________________________________________________

In [ ]:
#history = model.fit([inputs_train,queries_train], answers_train,batch_size=32, epochs=3, verbose=2, validation_data=([inputs_test,queries_test],answers_test))

In [ ]:
import IPython
print(IPython.sys_info())

{'commit_hash': 'b467d487e',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.6/dist-packages/IPython',
 'ipython_version': '5.5.0',
 'os_name': 'posix',
 'platform': 'Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.6.9 (default, Apr 18 2020, 01:56:04) \n[GCC 8.4.0]'}


In [ ]:
'''
import matplotlib.pyplot as plt
#%matplotlib.inline
print(history,history.keys())
#summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model_accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
'''

NameError: ignored

In [ ]:
model.load_weights('chatbot_10.h5')

pred_results = model.predict(([inputs_test,queries_test]))

In [ ]:
print(test_data[0][0],
test_data[0][1],
test_data[0][2])

['Mary', 'got', 'the', 'milk', 'there', '.', 'John', 'moved', 'to', 'the', 'bedroom', '.'] ['Is', 'John', 'in', 'the', 'kitchen', '?'] no


In [ ]:
val_max = np.argmax(pred_results[0])

In [ ]:
for key,val in tokenizer.word_index.items():
    if val == val_max:
       k = key

In [ ]:
k

'down'

In [ ]:
pred_results[0][val_max]

0.7665366